spring:
  application:
    name: streamsocial-producer-service

server:
  port: 8081

streamsocial:
  kafka:
    bootstrap-servers: localhost:29092,localhost:29093,localhost:29094

logging:
  level:
    org.apache.kafka: WARN
    com.streamsocial: INFO
