server:
  port: 8082

spring:
  application:
    name: streamsocial-producer-service
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092,localhost:9093,localhost:9094}

management:
  endpoints:
    web:
      exposure:
        include: health
