spring:
  application:
    name: streamsocial-engagement-consumer
  main:
    web-application-type: none

streamsocial:
  kafka:
    bootstrap-servers: localhost:9092,localhost:9093,localhost:9094

logging:
  level:
    org.apache.kafka: WARN
    com.streamsocial: INFO
